Namespace(batch_size=500, cell_type='LSTM', data_file='./data/csv_900.p', embedding_size=32, file=None, hidden_size=128, max_examples=1, max_length=15, min_examples=1, min_iterations=1000, n_examples=100, n_tasks=25, skip_tasks=0)
Loading csv_900.p, ignoring data params.
Created network
/om/user/lbh/text-patterns/pinn/robustfill.py:109: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  return score.data[0]

Calculating train_seen error
0 / 100
10 / 100
20 / 100
30 / 100
40 / 100
50 / 100
60 / 100
70 / 100
80 / 100
90 / 100
Score: -34.335048332214356

Calculating train_unseen error
0 / 100
10 / 100
20 / 100
30 / 100
40 / 100
50 / 100
60 / 100
70 / 100
80 / 100
90 / 100
Score: -34.36537609100342

Calculating test error
0 / 100
10 / 100
20 / 100
30 / 100
40 / 100
50 / 100
60 / 100
70 / 100
80 / 100
90 / 100
Score: -40.05429534912109
Scores: seen -34.335048332214356 unseen -34.36537609100342 test -40.05429534912109
Iteration 10 | Network loss: 32.91
(['Leasehold'],) ---> 7{QtRSk)P
Iteration 20 | Network loss: 27.47
(['WA2 8QZ'],) ---> 4M3
Iteration 30 | Network loss: 28.22
(['HC-TEV-2D'],) ---> T
Iteration 40 | Network loss: 27.07
(['1.06'],) ---> 9CQ81
Iteration 50 | Network loss: 26.00
(['Pf3D7_03_v3'],) ---> 405_12Q%V6
Iteration 60 | Network loss: 26.13
(['5'],) ---> A_q39973
Iteration 70 | Network loss: 25.35
(['DFL-1100'],) ---> O2O826N296
Iteration 80 | Network loss: 25.47
(['76.62'],) ---> E.312
slurmstepd: error: *** JOB 10877651 ON node042 CANCELLED AT 2018-05-14T16:30:50 ***
